packages:
  - "apps/*"
  - "packages/**/*"
catalog:
  "react" : "19.1.1"
  "@types/react" : "19.1.12"
  "next" : "15.5.2"
  "@types/node": "24.3.1"
  "react-dom" : "19.1.1"
  "tailwindcss" : "4.1.7"
  "@tailwindcss/postcss" : "4.1.7"
  "postcss" : "8.5.6"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "lucide-react": "^0.542.0"
  "tailwind-merge": "^3.3.1"
  "tw-animate-css": "^1.3.8"
  "@bufbuild/protobuf": "^2.8.0"
  "grpc-web" : "^2.0.1"
  "google-protobuf" : "3.21.4"
