[project]
name = "python-grpc-server"
version = "0.1.0"
description = "Simple gRPC server using betterproto"
requires-python = ">=3.8"
dependencies = [
    "grpclib==0.4.4",
    "betterproto==2.0.0b7",
]

[tool.uv]
dev-dependencies = []
