[project]
name = "python-grpc-bindings"
version = "0.0.1"
description = "grpc bindings"
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["example"]
